apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnug-deployment
  namespace: lnug
  labels:
    app: lnug
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: lnug
  template:
    metadata:
      labels:
        app: lnug
    spec:
      containers:
      - name: lnug
        image: {{ .Values.docker.image }}:{{ .Values.docker.tag }}
        env:
        - name: PORT
          value: "3000"
        - name: IP_ADDRESS
          value: "0.0.0.0"
        resources:
          limits:
            cpu: "200m"
            memory: "50Mi"
          requests:
            cpu: "100m"
            memory: "25Mi"
        ports:
        - containerPort: {{ .Values.networking.port }}
