apiVersion: v1
kind: Service
metadata:
  name: lnug-service
  namespace: lnug
spec:
  type: NodePort
  selector:
    app: lnug
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.networking.port }}
